name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [development, staging, production]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build .NET App
        run: dotnet build --configuration Release

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [development, staging, production]
    environment: ${{ matrix.environment }}  # Enables GitHub Environment approvals

    # ✅ Correctly calling the reusable workflow
    uses: yevhenkainaraideals/github-pipeline-templates-public/.github/workflows/deploy.yml@main
    with:
      environment: ${{ matrix.environment }}
      aws_region: ${{ vars.AWS_REGION }}
      resource_prefix: ${{ vars.RESOURCE_PREFIX }}
    secrets:
      AWS_SECRET: ${{ secrets.AWS_SECRET }}
