name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build .NET App
        run: dotnet build --configuration Release

      - name: Run Tests
        run: dotnet test --configuration Release

  deploy:
    needs: build
    strategy:
      matrix:
        environment: [development, staging, production]
    # ✅ Calls the reusable deployment workflow
    uses: yevhenkainaraideals/github-pipeline-templates-public/.github/workflows/deploy.yml@main
    with:
      environment: ${{ matrix.environment }}
      aws_region: ${{ vars.AWS_REGION }}
      resource_prefix: ${{ vars.RESOURCE_PREFIX }}
    secrets:
      AWS_SECRET: ${{ secrets.AWS_SECRET }}
